---
- name: Install dependencies
  apt: >
    pkg=python-software-properties
    state=installed
    update-cache=yes

- name: Add repository
  apt_repository: >
    repo=ppa:chris-lea/redis-server
    state=present

- name: Install latest version
  apt: >
    pkg={{ item }}
    state=installed
    update-cache=yes
  register: redis_install
  with_items:
    - redis-server

- name: Disable obsolete init.d service
  service: >
    name=redis-server
    enabled=no
    state=stopped

- name: Remove obsolete init.d service
  file:
    path: /etc/init.d/redis-server
    state: absent

- name: Install init script
  template: >
    src=root/etc/init/redis-server.conf.j2
    dest=/etc/init/redis-server.conf
  notify:
    - restart redis

- name: Create data directory
  file: >
    state=directory
    path={{ redis.config.dir }}
    owner={{ redis.user }}
    group={{ redis.group }}
    recurse=yes

- name: Install config
  template: >
    src=root/etc/redis/redis.conf.j2
    dest=/etc/redis/redis.conf
  notify:
    - restart redis

- name: restart redis
  service: >
    name=redis-server
    state=restarted



# - name: Install monit configuration
#   template: >
#     src=root/etc/monit/conf.d/redis.j2
#     dest=/etc/monit/conf.d/redis
#   notify: restart monit
