# common.yml
#   Setup common to all hosts
#
# This software is public domain.
#

- name: Common Server Setup
  hosts: all
  sudo: yes
  tasks:
    # - name: Update apt cache and upgrade base packages
    #   tags:
    #     - update-packages
    #   apt: update_cache=yes upgrade=yes

    - name: Create canvas user
      tags:
        - config-app
      user: name={{ canvas_service_account }} comment="Canvas Service Account" shell=/bin/bash
