---
- name: configure accounts db servers
  hosts: all
  sudo: true
  roles:
    - { role: common, sudo: yes }
    - role: postgres
      postgresql_version: 9.5

- name: initialize database
  hosts: all
  sudo: true
  tasks:
    - include_vars: vars/accounts.yml
    - include: tasks/init_app_db.yml
      app_name: accounts
      app_db_name: "{{ accounts_db_name }}"
      app_db_user: "{{ accounts_db_user }}"
      app_db_password: "{{ accounts_db_password }}"
      run_once: true

- name: set up envs
  hosts: all
  sudo: true
  sudo_user: vagrant
  vars:
    - ruby_version: 2.3.3
  roles:
    - role: anyenv
    - role: simple_ruby
