---
- name: configure tutor db servers
  hosts: all
  sudo: true
  roles:
    - { role: common, sudo: yes }
    - role: postgres
      postgresql_version: 9.5
    - role: redis

- name: initialize tutor database
  hosts: all
  sudo: true
  pre_tasks:
    - include_vars: vars/tutor.yml
    - include: tasks/init_app_db.yml
      app_name: tutor
      app_db_name: "{{ tutor_db_name }}"
      app_db_user: "{{ tutor_db_user }}"
      app_db_password: "{{ tutor_db_password }}"
      run_once: true
  roles:
    - role: pgext
      run_once: true
      pgext_db: "{{ tutor_db_name }}"
      pgext_superuser: "{{ pg_user }}"
      pgext_super_password: ""
      pgext_host: "localhost"
      pgext_extensions:
        - plpgsql
        - hstore
        - pgcrypto


- name: set up envs
  hosts: all
  sudo: true
  sudo_user: vagrant
  vars:
    - ruby_version: 2.2.3
  roles:
    - role: anyenv
    - role: simple_ruby
