---
- name: psql check
  debug:
    msg: "check for psql"
  tags:
    - debug

- name: check if psql is installed
  shell: >
    type -P psql
  args:
    executable: /bin/bash
  register: psql_loc
  failed_when: psql_loc.stderr

- name: set psql facts
  set_fact:
    psql_install: "{{ psql_loc.rc|default(1) != 0 }}"
