test:
  adapter: postgresql
  encoding: utf8
  database: {{ canvas_db.test.name }}
  host: {{ canvas_db.test.host }}
  username: {{ canvas_db.test.user }}
  password: {{ canvas_db.test.password }}
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: {{ canvas_db.development.name }}
  host: {{ canvas_db.development.host }}
  username: {{ canvas_db.development.user }}
  password: {{ canvas_db.development.password }}
  timeout: 5000
  queue:
    adapter: postgresql
    encoding: utf8
    database: {{ canvas_db.development_queue.name }}
    host: {{ canvas_db.development_queue.host }}
    username: {{ canvas_db.development_queue.user }}
    password: {{ canvas_db.development_queue.password }}
    timeout: 5000
