---
- name: Set hostname
  hostname: >
    name={{ hostname_override }}
  when: hostname_override is defined

- name: Set timezone to UTC
  shell: >
    echo Etc/UTC > /etc/timezone

- name: Set localtime to UTC
  file: >
    src=/usr/share/zoneinfo/Etc/UTC
    dest=/etc/localtime

- name: Reconfigure tzdata
  command: >
    dpkg-reconfigure -f noninteractive tzdata

- name: Update apt keys
  command: >
    apt-key update

# - name: Run apt-get update
#   command: >
#     apt-get update

# - name: Upgrade apt
#   apt: >
#     upgrade=yes

# - name: install latest stable rsyslogd
#   apt: name=rsyslog update_cache=yes state=latest
#   tags: rsyslog

- name: Install packages
  apt: >
    pkg={{ item }}
    state=installed
    force=yes
  with_items:
    - ubuntu-keyring
    - build-essential
    - curl
    - emacs24-nox
    - libicu-dev
    - python-boto
    - git-core
    - unzip
    - imagemagick
    - zlib1g-dev
    - libxml2-dev
    - libmysqlclient-dev
    - libxslt1-dev
    - libpq-dev
    - libxmlsec1-dev
    - libcurl4-gnutls-dev
    - libxmlsec1
    - libsqlite3-dev
    - libreadline-dev
