---
- name: rbenv installation
  debug:
    msg: "{{ install }}"
  tags:
    - debug

- name: rbenv install location
  debug:
    msg: "{{ rbenv_root }}"
  tags:
    - debug

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: yes
    update_cache: yes
  with_items: "{{ rbenv.packages }}"
  tags:
    - rbenv-apt
    - apt

- name: pull rbenv source
  sudo_user: "{{ app_user }}"
  git: >
    repo=https://github.com/rbenv/rbenv.git
    dest={{ rbenv_root }}
  tags:
    - rbenv-upgrade

- name: add rbenv to path
  file: >
    path=/usr/local/bin/rbenv
    src={{ rbenv_root }}/bin/rbenv
    state=link
  tags:
    - rbenv-initialize

- name: initialize rbenv
  template: >
    src=etc/profile.d/rbenv.sh.j2
    dest=/etc/profile.d/rbenv.sh
    owner=root
    group=root
    mode=0755
  tags:
    - rbenv-initialize

- name: intialize rbenv for app user
  shell: >
    cat /etc/profile.d/rbenv.sh >> {{app_user_home}}/.profile
  tags:
    - rbenv-initialize
