---
- name: Install dependencies
  apt: >
    name="{{item}}"
    state=present
  with_items: ["python-psycopg2", "python-pycurl"]

- name: Add repository key
  apt_key: >
    url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id=ACCC4CF8
    state=present

- name: Add official repository
  apt_repository: >
    repo="deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main"
    state=present

- name: Install latest version
  apt: >
    pkg="{{item}}"
    state=latest
    update_cache=yes
    cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - "postgresql-{{postgresql_version}}"
    - "postgresql-client-{{postgresql_version}}"

- name: Install pg_hba configuration
  template: >
    src=root/etc/postgresql/pg_hba.conf.j2
    dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf

- name: restart postgresql
  service: >
    name=postgresql
    state=restarted

