######################################################################
# ruby setup
#

- name: Install Ruby
  tags:
    - update-ruby
  args:
    executable: /bin/bash
  register: install_ruby
  changed_when: install_ruby.stdout != ""
  environment:
    CONFIGURE_OPTS: "--disable-install-doc"
  shell: |
    source ~/anyenv.sh &&
    rbenv install -s {{ ruby_version }}

# - name: Install bundler gem
#   tags:
#     - update-ruby
#     - update-gems
#     - update-libs
#   gem: executable={{ gem_executable }} name={{ item.name }} version={{ item.version }} user_install=no
#   with_items: "{{ base_gems }}"

- name: Rehash rbenv binaries
  tags:
    - update-ruby
  args:
    executable: /bin/bash
  changed_when: False
  shell: |
    source ~/anyenv.sh &&
    rbenv rehash
